### ISSUE TITLE
Support for Ollama Planned/Possible?

### ISSUE THREAD

**Issue by Heavy02011** [lm-sys/RouteLLM#2]
Any ideas / plans to support ollama? 
maybe following a similar approach as for [TextGrad](https://github.com/zou-group/textgrad/pull/5) which runs perfectly on an embedded device like Jetson Orin.

PS. Awesome work, thx for sharing.

**Comment by iojw** [comment]
Hi there! Since Ollama supports an OpenAI-compatible server (https://ollama.com/blog/openai-compatibility), you can already use it with RouteLLM. Just launch the Ollama server, specify the `--alt-base-url` flag to point to your local server, and everything should work.

I'll update the README to make this clearer.
