### ISSUE TITLE
Support for Amazon Bedrock Routers

### ISSUE THREAD

**Issue by dferguson992** [lm-sys/RouteLLM#3]
Add router support for models hosted on Amazon Bedrock.

**Comment by iojw** [comment]
Hi there! We support any provider that has a OpenAI-compatible interface, including Amazon Bedrock. You can view instructions for setting up an OpenAI-compatible interface for Amazon Bedrock models here: https://github.com/aws-samples/bedrock-access-gateway

Let me know if you have any questions setting it up.

**Comment by iojw** [comment]
@dferguson992 We are looking to add LiteLLM support very soon (https://github.com/lm-sys/RouteLLM/pull/11), which should make it even easier to integrate Amazon Bedrock. Instead of having to deploy a CF stack, you now only need to set the API keys for your account. Let us know if you have any thoughts.
