### ISSUE TITLE
Question: was text-embedding-3-small included in the bills?

### ISSUE THREAD

**Issue by Sunt-ing** [lm-sys/RouteLLM#5]
Hi developers, thanks for your effort on this project! 

I have a question: in the paper, when calculating router monetary costs, were the costs of the OpenAI embedding model (i.e., text-embedding-3-small) included?

**Comment by iojw** [comment]
Hi, are you referring to the cost savings section (4.4) in the paper? For this, we calculated cost savings based on the number of GPT-4 calls only, since this is the much greater (>100x) as compared to the cost for Mixtral 8x7B and embedding calls.

GPT-4: ~$20 / M tokens
Mixtral: ~$0.20 / M tokens
text-embedding-3-small: $0.02 / M tokens.

**Comment by Sunt-ing** [comment]
Thanks for your calculation!
